//go:build ignore

// gen_known writes zz_generated_known.go: the sorted <os>/<arch> ports that
// `go tool dist list` reports, and the Go release (major.minor) that reported
// them. Run it with `task generate` (go generate). go generate sets GOROOT to
// the toolchain running it, so the list is that toolchain's.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
)

func main() {
	// runtime.GOROOT is deprecated; go generate exports GOROOT instead. Fall
	// back to "go" from PATH, where go generate puts the same toolchain first.
	goBin := "go"
	if root := os.Getenv("GOROOT"); root != "" {
		goBin = filepath.Join(root, "bin", "go")
	}

	ver, err := exec.Command(goBin, "env", "GOVERSION").Output()
	if err != nil {
		log.Fatalf("go env GOVERSION: %v", err)
	}
	goVersion := regexp.MustCompile(`^go[0-9]+\.[0-9]+`).FindString(strings.TrimSpace(string(ver)))
	if goVersion == "" {
		log.Fatalf("go env GOVERSION printed %q, which does not start with go<major>.<minor>", ver)
	}

	out, err := exec.Command(goBin, "tool", "dist", "list").Output()
	if err != nil {
		log.Fatalf("go tool dist list: %v", err)
	}
	ports := strings.Fields(string(out))
	if len(ports) == 0 {
		log.Fatal("go tool dist list printed no ports")
	}
	slices.Sort(ports)

	var b bytes.Buffer
	b.WriteString("// Code generated by gen_known.go from `go tool dist list`; DO NOT EDIT.\n\n")
	b.WriteString("package platform\n\n")
	b.WriteString("// generatedGoVersion is the Go release whose `go tool dist list` produced\n")
	b.WriteString("// knownPorts. The drift test compares the list only on that release.\n")
	fmt.Fprintf(&b, "const generatedGoVersion = %q\n\n", goVersion)
	b.WriteString("// knownPorts is the producer allow-list: every <os>/<arch> pair the Go\n")
	b.WriteString("// toolchain supports, sorted for binary search.\n")
	b.WriteString("var knownPorts = []string{\n")
	for _, p := range ports {
		fmt.Fprintf(&b, "\t%q,\n", p)
	}
	b.WriteString("}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("format generated source: %v", err)
	}
	if err := os.WriteFile("zz_generated_known.go", src, 0o644); err != nil {
		log.Fatalf("write zz_generated_known.go: %v", err)
	}
}
